language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
branches:
  only:
    - master
services:
  - redis-server
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - py.test
after_success:
  - pip install python-coveralls
  - coveralls
